# Generated by Django 4.0.4 on 2022-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scimag',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doi', models.CharField(db_column='DOI', max_length=200, unique=True)),
                ('doi2', models.CharField(db_column='DOI2', max_length=100)),
                ('title', models.CharField(db_column='Title', max_length=2000)),
                ('author', models.CharField(db_column='Author', max_length=2000)),
                ('year', models.CharField(db_column='Year', max_length=10)),
                ('month', models.CharField(db_column='Month', max_length=10)),
                ('day', models.CharField(db_column='Day', max_length=10)),
                ('volume', models.CharField(db_column='Volume', max_length=45)),
                ('issue', models.CharField(db_column='Issue', max_length=95)),
                ('first_page', models.CharField(db_column='First_page', max_length=45)),
                ('last_page', models.CharField(db_column='Last_page', max_length=45)),
                ('journal', models.CharField(db_column='Journal', max_length=500)),
                ('isbn', models.CharField(db_column='ISBN', max_length=500)),
                ('issnp', models.CharField(db_column='ISSNP', max_length=11)),
                ('issne', models.CharField(db_column='ISSNE', max_length=10)),
                ('md5', models.CharField(db_column='MD5', max_length=32)),
                ('filesize', models.PositiveIntegerField(db_column='Filesize')),
                ('timeadded', models.DateTimeField(db_column='TimeAdded')),
                ('journalid', models.CharField(db_column='JOURNALID', max_length=45)),
                ('abstracturl', models.CharField(db_column='AbstractURL', max_length=500)),
                ('attribute1', models.CharField(db_column='Attribute1', max_length=500)),
                ('attribute2', models.CharField(db_column='Attribute2', max_length=1000)),
                ('attribute3', models.CharField(db_column='Attribute3', max_length=2000)),
                ('attribute4', models.CharField(blank=True, db_column='Attribute4', max_length=5000, null=True)),
                ('attribute5', models.CharField(db_column='Attribute5', max_length=256)),
                ('attribute6', models.CharField(db_column='Attribute6', max_length=45)),
                ('visible', models.CharField(max_length=3)),
                ('pubmedid', models.CharField(db_column='PubmedID', max_length=10)),
                ('pmc', models.CharField(db_column='PMC', max_length=12)),
                ('pii', models.CharField(db_column='PII', max_length=45)),
            ],
            options={
                'db_table': 'scimag',
                'managed': False,
            },
        ),
    ]
