# Generated by Django 4.0.4 on 2022-06-16 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_scimag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('doi', models.CharField(db_column='DOI', max_length=200, unique=True)),
                ('preprint', models.CharField(max_length=200, verbose_name='Ссылка на препринт')),
                ('copy', models.CharField(max_length=200, verbose_name='Ссылка на копию')),
                ('authors', models.TextField(verbose_name='Список авторов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
