# Generated by Django 4.0.4 on 2022-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_doi_tab_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='authors',
            field=models.TextField(max_length=200, null=True, verbose_name='Список авторов'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='copy',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на копию'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='preprint',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на препринт'),
        ),
    ]
