# Generated by Django 4.0.4 on 2022-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tab_authors_alter_tab_copy_alter_tab_preprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='source',
            field=models.CharField(db_column='DOI', max_length=200, null=True, unique=True),
        ),
    ]
